service: our-course
frameworkVersion: '3'

custom:
  secrets: ${file(secrets.json)}
  bundle:
    ignorePackages:
      - pg-native

plugins: 
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}

# just for checkt db connection
functions:
  healthCheck:
    handler: index.healthCheck
    events:
      - http:
          path: /
          method: get
  # manage users
  userRegister:
    handler: index.register
    events:
      - http:
          path: users/register
          method: post
  userLogin:
    handler: index.login
    events:
      - http:
          path: users/login
          method: post
  #manage course
  addCourse:
    handler: index.addCourse
    events:
      - http:
          path: courses
          method: post
  listCourse:
    handler: index.listCourse
    events:
      - http:
          path: courses
          method: get
  getCourse:
    handler: index.getCourse
    events:
      - http:
          path: courses/{id}
          method: get
  updateCourse:
    handler: index.updateCourse
    events:
      - http:
          path: courses/{id}
          method: put
  deleteCourse:
    handler: index.deleteCourse
    events:
      - http:
          path: courses/{id}
          method: delete
  # user course
  userListCourse:
    handler: index.userListCourse
    events:
      - http:
          path: users/courses
          method: get
  userGetCourse:
    handler: index.userGetCourse
    events:
      - http:
          path: users/courses/{id}
          method: get
  userEnrollCourse:
    handler: index.userEnrollCourse
    events:
      - http:
          path: users/courses/{id}
          method: post
